/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppAiCenterRouteImport } from './routes/_app.ai-center'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppBedsRouteImport } from './routes/_app.beds'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppDoctorsRouteImport } from './routes/_app.doctors'
import { Route as AppEmergencyRouteImport } from './routes/_app.emergency'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppLaboratoryRouteImport } from './routes/_app.laboratory'
import { Route as AppMedicalRecordsRouteImport } from './routes/_app.medical-records'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRecordsRouteImport } from './routes/_app.records'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiCenterRoute = AppAiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppBedsRoute = AppBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppLaboratoryRoute = AppLaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRecordsRoute = AppMedicalRecordsRouteImport.update({
  id: '/medical-records',
  path: '/medical-records',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/ai-center': typeof AppAiCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/beds': typeof AppBedsRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/doctors': typeof AppDoctorsRoute
  '/emergency': typeof AppEmergencyRoute
  '/inventory': typeof AppInventoryRoute
  '/laboratory': typeof AppLaboratoryRoute
  '/medical-records': typeof AppMedicalRecordsRoute
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/profile': typeof AppProfileRoute
  '/records': typeof AppRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/ai-center': typeof AppAiCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/beds': typeof AppBedsRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/doctors': typeof AppDoctorsRoute
  '/emergency': typeof AppEmergencyRoute
  '/inventory': typeof AppInventoryRoute
  '/laboratory': typeof AppLaboratoryRoute
  '/medical-records': typeof AppMedicalRecordsRoute
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/profile': typeof AppProfileRoute
  '/records': typeof AppRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/ai-center': typeof AppAiCenterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/beds': typeof AppBedsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/doctors': typeof AppDoctorsRoute
  '/_app/emergency': typeof AppEmergencyRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/laboratory': typeof AppLaboratoryRoute
  '/_app/medical-records': typeof AppMedicalRecordsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/pharmacy': typeof AppPharmacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-center'
    | '/analytics'
    | '/appointments'
    | '/beds'
    | '/billing'
    | '/dashboard'
    | '/departments'
    | '/doctors'
    | '/emergency'
    | '/inventory'
    | '/laboratory'
    | '/medical-records'
    | '/notifications'
    | '/patients'
    | '/pharmacy'
    | '/profile'
    | '/records'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-center'
    | '/analytics'
    | '/appointments'
    | '/beds'
    | '/billing'
    | '/dashboard'
    | '/departments'
    | '/doctors'
    | '/emergency'
    | '/inventory'
    | '/laboratory'
    | '/medical-records'
    | '/notifications'
    | '/patients'
    | '/pharmacy'
    | '/profile'
    | '/records'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/ai-center'
    | '/_app/analytics'
    | '/_app/appointments'
    | '/_app/beds'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/doctors'
    | '/_app/emergency'
    | '/_app/inventory'
    | '/_app/laboratory'
    | '/_app/medical-records'
    | '/_app/notifications'
    | '/_app/patients'
    | '/_app/pharmacy'
    | '/_app/profile'
    | '/_app/records'
    | '/_app/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai-center': {
      id: '/_app/ai-center'
      path: '/ai-center'
      fullPath: '/ai-center'
      preLoaderRoute: typeof AppAiCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beds': {
      id: '/_app/beds'
      path: '/beds'
      fullPath: '/beds'
      preLoaderRoute: typeof AppBedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctors': {
      id: '/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emergency': {
      id: '/_app/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laboratory': {
      id: '/_app/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof AppLaboratoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-records': {
      id: '/_app/medical-records'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof AppMedicalRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AppRouteChildren {
  AppAiCenterRoute: typeof AppAiCenterRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppBedsRoute: typeof AppBedsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLaboratoryRoute: typeof AppLaboratoryRoute
  AppMedicalRecordsRoute: typeof AppMedicalRecordsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiCenterRoute: AppAiCenterRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppBedsRoute: AppBedsRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLaboratoryRoute: AppLaboratoryRoute,
  AppMedicalRecordsRoute: AppMedicalRecordsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPharmacyRoute: AppPharmacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
